name: automated-jobs
on: push
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run-truffle-tests
        run: |
          npm install chai
          npx truffle test