name: run-unit-tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run-truffle-tests
      - uses: actions/checkout@v2
      - run: |
          ls
          npx truffle test